name = "Subtype-Inference-Prover"
version = "0.1.0"
defaultTargets = ["subtype-inference-prover"]

[[lean_lib]]
name = "SubtypeInferenceProver"

[[lean_exe]]
name = "subtype-inference-prover"
root = "Main"
