name: Create Release

on:
  push:
    branches: [main, master]
    # If lean-toolchain is inside your project subdir, point to it here:
    paths:
      - '.c2rust/enum/Subtype-Inference/Prover/lean-toolchain'

jobs:
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Many actions need the workspace checked out
      - uses: actions/checkout@v4

      - name: lean-release-tag action
        uses: leanprover-community/lean-release-tag@v1
        with:
          do-release: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
