name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1

      - name: Build
        run: lake build -C ./c2rust/enum/Subtype-Inference/Prover

      - name: Test
        run: lake test -C ./c2rust/enum/Subtype-Inference/Prover
