name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./c2rust/enum/Subtype-Inference/Prover

    steps:
      - uses: actions/checkout@v4

      # Sets up Lean/elan etc. (runs at repo root; that's OK for setup)
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: c2rust/enum/Subtype-Inference/Prover
          
      # Build & test your project in (WD)
      - name: Build
        run: lake build

      - name: Test
        run: lake test
