name: Update Dependencies

on:
  # schedule:
  #   - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    # If the action needs to operate inside the project dir for checks,
    # set defaults.run. (If the action clones/works elsewhere, you can remove this.)
    defaults:
      run:
        working-directory: ./c2rust/enum/Subtype-Inference/Prover
    outputs:
      is-update-available: ${{ steps.check-for-updates.outputs.is-update-available }}
      new-tags: ${{ steps.check-for-updates.outputs.new-tags }}
    steps:
      - uses: actions/checkout@v4
      - name: Run the action
        id: check-for-updates
        uses: leanprover-community/mathlib-update-action@v1
        # START CONFIGURATION BLOCK 1
        # END CONFIGURATION BLOCK 1

  do-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: check-for-updates
    if: ${{ needs.check-for-updates.outputs.is-update-available }}
    strategy:
      max-parallel: 1
      matrix:
        tag: ${{ fromJSON(needs.check-for-updates.outputs.new-tags) }}
    defaults:
      run:
        working-directory: ./c2rust/enum/Subtype-Inference/Prover
    steps:
      - uses: actions/checkout@v4

      - name: Run the action
        id: update-the-repo
        uses: leanprover-community/mathlib-update-action/do-update@v1
        with:
          tag: ${{ matrix.tag }}
          # START CONFIGURATION BLOCK 2
          on_update_succeeds: pr
          on_update_fails: issue
          # END CONFIGURATION BLOCK 2
